# Build script for Windows - creates DocFinder.exe installer
#
# Prerequisites:
#   - Install NSIS: https://nsis.sourceforge.io/Download
#   - pip install '.[dev,gui]'
#
# Usage:
#   .\scripts\build-windows.ps1

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$ResourcesDir = Join-Path $ProjectRoot "resources"
$DistDir = Join-Path $ProjectRoot "dist"
$BuildDir = Join-Path $ProjectRoot "build"

Write-Host "=== DocFinder Windows Build Script ===" -ForegroundColor Cyan
Write-Host "Project root: $ProjectRoot"

# Create resources directory if it doesn't exist
if (-not (Test-Path $ResourcesDir)) {
    New-Item -ItemType Directory -Path $ResourcesDir | Out-Null
}

# Convert Logo.png to .ico if needed
$LogoPng = Join-Path $ProjectRoot "Logo.png"
$IcoFile = Join-Path $ResourcesDir "DocFinder.ico"

if (Test-Path $LogoPng) {
    Write-Host "Converting Logo.png to .ico..."
    
    # Use PowerShell to convert PNG to ICO
    # This requires .NET Framework which is available on all Windows
    Add-Type -AssemblyName System.Drawing
    
    $image = [System.Drawing.Image]::FromFile($LogoPng)
    
    # Create multiple sizes for the ICO
    $sizes = @(16, 32, 48, 64, 128, 256)
    $icons = @()
    
    foreach ($size in $sizes) {
        $bitmap = New-Object System.Drawing.Bitmap($size, $size)
        $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
        $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $graphics.DrawImage($image, 0, 0, $size, $size)
        $graphics.Dispose()
        $icons += $bitmap
    }
    
    # Save as ICO using the largest size (Windows will use appropriate size)
    $icon = [System.Drawing.Icon]::FromHandle($icons[-1].GetHicon())
    $fileStream = [System.IO.File]::Create($IcoFile)
    $icon.Save($fileStream)
    $fileStream.Close()
    
    foreach ($bmp in $icons) {
        $bmp.Dispose()
    }
    $image.Dispose()
    
    Write-Host "Created $IcoFile"
} else {
    Write-Host "Warning: Logo.png not found, building without custom icon" -ForegroundColor Yellow
}

# Clean previous builds
Write-Host "Cleaning previous builds..."
if (Test-Path (Join-Path $DistDir "DocFinder")) {
    Remove-Item -Recurse -Force (Join-Path $DistDir "DocFinder")
}
if (Test-Path (Join-Path $BuildDir "DocFinder")) {
    Remove-Item -Recurse -Force (Join-Path $BuildDir "DocFinder")
}

# Run PyInstaller
Write-Host "Running PyInstaller..."
Set-Location $ProjectRoot
pyinstaller DocFinder.spec --clean --noconfirm

# Verify the build was created
$ExePath = Join-Path $DistDir "DocFinder" "DocFinder.exe"
if (-not (Test-Path $ExePath)) {
    Write-Host "Error: DocFinder.exe was not created" -ForegroundColor Red
    exit 1
}

Write-Host "DocFinder built successfully" -ForegroundColor Green

# Create NSIS installer script
$NsisScript = Join-Path $DistDir "DocFinder-installer.nsi"

$NsisContent = @"
; DocFinder NSIS Installer Script
; Generated by build-windows.ps1

!include "MUI2.nsh"

; General
Name "DocFinder"
OutFile "DocFinder-Setup.exe"
InstallDir "`$PROGRAMFILES64\DocFinder"
InstallDirRegKey HKLM "Software\DocFinder" "Install_Dir"
RequestExecutionLevel admin

; Interface Settings
!define MUI_ABORTWARNING
!define MUI_ICON "$ResourcesDir\DocFinder.ico"
!define MUI_UNICON "$ResourcesDir\DocFinder.ico"

; Pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Languages
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Italian"

; Installer Sections
Section "DocFinder" SecMain
    SetOutPath "`$INSTDIR"
    
    ; Copy all files from dist/DocFinder
    File /r "$DistDir\DocFinder\*.*"
    
    ; Create uninstaller
    WriteUninstaller "`$INSTDIR\Uninstall.exe"
    
    ; Create Start Menu shortcuts
    CreateDirectory "`$SMPROGRAMS\DocFinder"
    CreateShortcut "`$SMPROGRAMS\DocFinder\DocFinder.lnk" "`$INSTDIR\DocFinder.exe"
    CreateShortcut "`$SMPROGRAMS\DocFinder\Uninstall.lnk" "`$INSTDIR\Uninstall.exe"
    
    ; Create Desktop shortcut
    CreateShortcut "`$DESKTOP\DocFinder.lnk" "`$INSTDIR\DocFinder.exe"
    
    ; Write registry keys
    WriteRegStr HKLM "Software\DocFinder" "Install_Dir" "`$INSTDIR"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\DocFinder" "DisplayName" "DocFinder"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\DocFinder" "UninstallString" "`$INSTDIR\Uninstall.exe"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\DocFinder" "DisplayIcon" "`$INSTDIR\DocFinder.exe"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\DocFinder" "Publisher" "DocFinder Team"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\DocFinder" "DisplayVersion" "1.1.1"
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\DocFinder" "NoModify" 1
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\DocFinder" "NoRepair" 1
SectionEnd

; Uninstaller Section
Section "Uninstall"
    ; Remove files
    RMDir /r "`$INSTDIR"
    
    ; Remove shortcuts
    Delete "`$SMPROGRAMS\DocFinder\*.*"
    RMDir "`$SMPROGRAMS\DocFinder"
    Delete "`$DESKTOP\DocFinder.lnk"
    
    ; Remove registry keys
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\DocFinder"
    DeleteRegKey HKLM "Software\DocFinder"
SectionEnd
"@

# Write NSIS script
$NsisContent | Out-File -FilePath $NsisScript -Encoding UTF8

Write-Host "NSIS script created at: $NsisScript"

# Try to build installer with NSIS
$MakeNsis = "C:\Program Files (x86)\NSIS\makensis.exe"
if (-not (Test-Path $MakeNsis)) {
    $MakeNsis = "C:\Program Files\NSIS\makensis.exe"
}

if (Test-Path $MakeNsis) {
    Write-Host "Building installer with NSIS..."
    Set-Location $DistDir
    & $MakeNsis "DocFinder-installer.nsi"
    
    if (Test-Path (Join-Path $DistDir "DocFinder-Setup.exe")) {
        Write-Host ""
        Write-Host "=== Build Complete ===" -ForegroundColor Green
        Write-Host "App:       $ExePath"
        Write-Host "Installer: $(Join-Path $DistDir 'DocFinder-Setup.exe')"
    }
} else {
    Write-Host ""
    Write-Host "Warning: NSIS not found. Install from https://nsis.sourceforge.io/Download" -ForegroundColor Yellow
    Write-Host "NSIS script saved to: $NsisScript"
    Write-Host "You can find the portable app at: $DistDir\DocFinder\"
}

Write-Host ""
Write-Host "To install:"
Write-Host "  1. Run DocFinder-Setup.exe"
Write-Host "  2. If SmartScreen appears, click 'More info' > 'Run anyway'"
